# Generated by Django 5.1.5 on 2025-01-27 04:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userformtemplate",
            name="unique_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
