# Generated by Django 5.1.5 on 2025-01-27 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_formresponse"),
    ]

    operations = [
        migrations.RenameField(
            model_name="formresponse",
            old_name="form_uuid",
            new_name="form_template",
        ),
    ]
